
# html lang
language: en

# main menu navigation
menu:
  Home: /
  About: /about
  Contact: /contact
  Archives: /archives


# post configuration
post: 
  showComments: false

# for seo
keywords: roam 
